### ISSUE TITLE
Update to tokio 0.1

### ISSUE THREAD

**Issue by o01eg** [astro/tokio-xmpp#2]
Tokio library made reorganization and moved from `tokio-core` to `tokio`, `tokio-reactor` and so on.

Are any plans to upgrade to it?

**Comment by astro** [comment]
Once the interfaces have stabilized, I would like to update this project. But no immediate plans.

**Comment by astro** [comment]
Please have a look at v0.1.1

**Comment by o01eg** [comment]
Looks like tokio-tls'd just upgraded https://github.com/tokio-rs/tokio-tls/pull/45

**Comment by o01eg** [comment]
`tokio-tls` 0.2.0 released. Instead of `domain` it possible to use `tokio-dns-unofficial` which supports `tokio`.
